version: "3"
services:
  frontend:
    container_name: frontend
    restart: always
    image: esdrastochi/frontend_ayd1
    ports:
      - "3000:3000"
    networks:
      - app_network
    depends_on:
      - backend

  backend:
    container_name: backend
    restart: always
    image: esdrastochi/backend_ayd1
    ports:
      - "3001:3001"
    networks:
      - app_network

networks:
  app_network:
    driver: bridge
